### ISSUE TITLE
Error when training is started..

### ISSUE THREAD

**Issue by funnymomo** [dvschultz/stylegan2-ada#14]
Hi.. getting error in training...dataset creation worked just fine.. 
(my images are 512x512)..downloaded your repo today only..

Any idea what could be wrong ?

Traceback (most recent call last):
  File "train.py", line 614, in <module>
    main()
  File "train.py", line 606, in main
    run_training(**vars(args))
  File "train.py", line 460, in run_training
    run_desc, training_options = setup_training_options(**hyperparam_options)
  File "train.py", line 108, in setup_training_options
    dataset_obj = dataset.load_dataset(**args.train_dataset_args) # try to load the data and see what comes out
  File "/content/drive/MyDrive/colab-sg2-ada/stylegan2-ada/training/dataset.py", line 272, in load_dataset
    mirror_augment=mirror_augment, mirror_augment_v=mirror_augment_v, repeat=repeat, shuffle=shuffle)
  File "/content/drive/MyDrive/colab-sg2-ada/stylegan2-ada/training/dataset.py", line 99, in _init_
    assert all(shape[0] == max_shape[0] for shape in tfr_shapes)
AssertionError

**Comment by funnymomo** [comment]
One more comment, I tried with set of different images.. and they worked. So I guess there was something wrong with my original dataset. They were originally greyscale.. which I had converted with imagemagic to add RGB and Truecolor .

**Comment by dvschultz** [comment]
that assertion error says somethings wrong with an image or images in your dataset. I’d double check to make sure they are all exactly 512x512
